### ISSUE TITLE
NFL Not pulling team names

### ISSUE THREAD

**Issue by ekosman87** [koolsb/fpp-nfl#7]
On the NFL side of the app, the "Teams" drop down is not populating any teams.
<img width="1384" alt="Screenshot 2023-09-10 at 1 18 17 PM" src="https://github.com/koolsb/fpp-nfl/assets/76722723/cf7bfe4b-1f28-4063-b88a-1ead1ff3ad61">

**Comment by nocturnaldev** [comment]
I found the cause and the solution.

For some reason, the non-secure address for the API endpoint is not working.  It's odd, because it works for other endpoints just fine.  Bottom line is that the secure version works as expected.  So -- just change "http" to "https" on the following line, and you're off to the races.

https://github.com/koolsb/fpp-nfl/blob/e6aab4c6c9f6e923519a28886dd67cdd35764f0f/functions.inc.php#L37C82-L37C82

**Comment by koolsb** [comment]
Updated API endpoint. Thanks @nocturnaldev for the find.
